### ISSUE TITLE
Specify in the ontology whether properties must/may be list-valued

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf#106]

**Comment by xrotwang** [comment]
@Anaphory you had issues regarding under-specification of cardinality, right? Which properties do you think need exact specs?

**Comment by Anaphory** [comment]
For #parameterReference, the new spec describing that it *must* be checked whether it is list-valued or singleton is good and what I needed.
For most other properties, I think having to check cardinality is bad: For example, #ids or #languageReferences with list values would be quite clearly nonsense, because it fundamentally contradicts how a dataset should work.
For some properties, it depends on context:
Having list-valued #parameterReferences makes sense for Wordlist data, but much less for a StructureDataset.
A BorrowingTable might make sense with list-valued #formReferences, but it would be weird in a #cognateTable.

**Comment by xrotwang** [comment]
Ok, I agree with your comment regarding `#id`. Reference properties OTOH can be used quite flexibly. Nothing prevents you from adding a `#languageReference` in a `countries.csv` table, linking to the languages spoken in a country. So as you said, it depends on context. It might be desirable/necessary to specify cardinality on the level of "particular property in particular component".

**Comment by Anaphory** [comment]
That sounds sensible.

**Comment by xrotwang** [comment]
I'd propose to specify cardinality as follows:
1. If a property **must not be list-valued**:
   ```
   <owl:cardinality>1</owl:cardinality>
   ```
2. If a property **must be list-valued**, the ontology specifies a `csvw:separator` which should be used by default.
3. Otherwise, the ontology specifies neither `owl:cardinality` nor `csvw:separator`.

**Comment by xrotwang** [comment]
New proposal: Use `dc:extent=singlevalued|multivalued`. This could be used
- in the ontology, to specify cardinality for all instances of a column
- in the column spec in the default metadata for component, to specify cardinality for a particular instance of a column.

**Comment by xrotwang** [comment]
See also https://github.com/cldf/cldf/blob/10d65582cbcc5528af82a179d5348a143ff8b1b3/components/values/README.md#valuetable-valuescsv
