### ISSUE TITLE
Using CodeID for numerical and multi-categorical data

### ISSUE THREAD

**Issue by davidainman** [cldf/cldf#109]
I was unsure whether to open this as a github issue or not, so please pardon me if it should be put elsewhere.

In our typological database there are two kinds of data we are keeping track of that are not simple categories. The first is numerical data (e.g., maximum number of consonants in coda, number of genders, etc). While I could create a CodeID for each discrete value in our dataset, this seems to me to break the idea of what a number is. I am currently putting the number value directly into the CodeID column in the values table. This seems unsupported, however, or if it is supported I could not find documentation explicitly making sure it was okay.

The second issue is similar: For some of our data, we allow a list or multiset from a discrete list of categories. An example is the set of semantic classes (kin, body parts, animals) for which a possessive construction can be used (this is useful for keeping track of what is in and out of alienability classes). We can list the set of classes in CodeID but it is not clear if it is supported to list multiple CodeIDs in the values table. As of right now, this is what I am doing, and I am separating the CodeIDs with semicolon <;>.

Both of these seem like valid use cases for linguistic data but it is not clear if they are supported by the formalism (if so, can this be documented? and if not, I humbly request their support) nor if they break downstream applications like CLLD.

**Comment by xrotwang** [comment]
@davidainman It's absolutely appropriate to post this as issue here! This is the kind of stuff that should be in an FAQ at some point.

**Comment by xrotwang** [comment]
Regarding your first question (I'll be using the term names from the ontology rather than the default column names): The `codeReference` column can be nullable, i.e. you can have values in your dataset, which do not reference a row in CodeTable. For these, you could put the number simply in the `value` column. You could even specify the datatype for the `value` column to be `integer`. But this may not be appropriate for other parameters in your dataset. But since these typed value columns are not specified by CLDF, a generic CLDF consumer would only look at strings in `value`, and would need to get the type information "out-of-band".

That's a bit of a weak spot in CLDF: Having parameters with different types of values in the same dataset is somewhat difficult - or rather requires a trade-off between full transparency and usability. For full transparency, you'd have to add typed columns to the ValueTable for each type - so the value for parameters with integer values would go into `Value_int`, or similar, while the value for parameters with dates as values would go into `Value_date`. A string representation of the values of any type could then go into the standard `value` column. Maybe some sort of specification of valid values in the ParameterTable would be a good candidate for CLDF 1.2.

**Comment by xrotwang** [comment]
Regarding the second question: multi-valued reference properties are supported in CLDF. So if you have a parameter "SemanticClasses", and rows in the CodeTable listing these classes, you could declare the `codeReference` column multivalued - by specifying a `separator` property (which seems what you have done?). Alternatively, you could just add multiple rows to ValueTable, each linked to just one code. While this would mean some duplication, it could also be appropriate, e.g. if you have separate sources for each link between construction and a single semantic class.

**Comment by xrotwang** [comment]
Here's an example how [D-PLACE](https://d-place.org/) deals with the problem of parameters with different value types: the ParameterTable specifies a column `datatype`, which provides "out-of-band" (i.e. non-CLDF-standardized) info how to interpret the values:
https://github.com/D-PLACE/dplace-cldf/blob/bca2e2de714aecc91d25c9b97aeb48ae15433c1d/cldf/StructureDataset-metadata.json#L297-L340)

The [CodeTable](https://github.com/D-PLACE/dplace-cldf/blob/master/cldf/codes.csv) only lists codes for the parameters specified as "categorical".

**Comment by xrotwang** [comment]
I could imagine a solution similar to the D-PLACE example above to be part of the CLDF spec. Maybe a bit more sophisticated, though, e.g. a column
```python
{
    "name": "datatype",
    "datatype": "string",
    "dc:format": "text/json"
}
```
in the ParameterTable, where the column content would be a [CSVW datatype description in JSON](https://www.w3.org/TR/tabular-metadata/#datatypes), e.g.
```python
{"base": "integer", "minimum": 0, "maximum": 20}
```

CLDF consumers could then use this datatype spec to read the data properly:
```python
>>> from csvw.metadata import Datatype
>>> import json
>>> dt = Datatype.fromvalue(json.loads('{"base": "integer", "maximum": 20}'))
>>> dt.read("17")
17
>>> dt.read("24")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robert_forkel/projects/cldf/csvw/src/csvw/metadata.py", line 343, in read
    return self.validate(self.parse(v))
  File "/home/robert_forkel/projects/cldf/csvw/src/csvw/metadata.py", line 339, in validate
    raise ValueError()
ValueError
```

**Comment by xrotwang** [comment]
@Anaphory @chrzyki @LinguList @SimonGreenhill what do you think about the "datatype" column sketched above? Too implicit or ad-hoc or weird (with JSON as column content in CSV)?

**Comment by Anaphory** [comment]
Independent of where to store the data type – this still doesn't make it very easy to store and properly handle closed-class and open-class data together, does it?

If I understand you correctly, even with this addition it would still require two different columns for 
1. the codes that are taken from a finite, parameter-dependent set and have their own metadata (eg. the decision tree to code YES vs. NO) in a CodeTable and
2. the open-class values, such as counts, that may have different data types specified using this suggested scheme.

Side remark: If we take ‘value’ to be the thing reported in some source, it's also not clear how to store data if the source claims a value is “11–13” and the data coder has to make an executive decision to get integers and goes always with the center. Where should the `11–13` go, where the `12`?

A data producer would have to fill those columns rigidly, and a data consumer would have to do a lot of case handling depending on which combination of data type, code reference, extracted value, (and raw value) columns are present, and which values they each have – this decision would need to be in the specs, so a data producer can rely on the data being handled consistently.

It could be that this is the best solution, but given the complexity, checking it thoroughly with some examples sounds good.

**Comment by xrotwang** [comment]
Well, maybe not "very easy", but as easy as possible - no? But yes, both reading and writing data would require consulting two places:

- Writing:
  1. Looking up a ParameterTable's "datatype" column. If it is non-null, use it to encode "value".
  2. Looking up CodeTable for codes associated with the parameter. If there are any, it's a categorical parameter and the row in ValueTable should have a non-null `codeReference`.

- Reading:
  1. If the row in ValueTable has non-null `codeReference`, just look up the code to get the value.
  2. If the referenced parameter has a "datatype" spec in ParameterTable, use it to decode "value".
 
A library such as `pycldf` could make this very transparent, I think.

**Comment by xrotwang** [comment]
@Anaphory Regarding the question of reported data vs. data for re-use: I think it's clear from your description and the design goals of CLDF what to do: CLDF wants to make data re-use easier, and apparently the "executive decision" to code a certain value as integer shares that goal (right?). So the integer should go into `value`, and the "raw" data should go somewhere else - `comment`, or a non-standard column.

**Comment by Anaphory** [comment]
Oh right, I thought we hat a sentence in the specs that #value is the original measurement or the value as given in the source. It's not in there, so of course that would go into a standard column.

**Comment by Anaphory** [comment]
Could we conceive a solution where the data type interpretation would be part of the CodeTable instead? I assume that's not compatible with csvw and in particular any clean implementation of foreignKeys, so I think your suggestion *is* the best one possible, but I'd at least want to consider how badly that would fail.

**Comment by xrotwang** [comment]
@Anaphory so how would that look like?

**Comment by chrzyki** [comment]
> 
> 
> @Anaphory @chrzyki @LinguList @SimonGreenhill what do you think about the "datatype" column sketched above? Too implicit or ad-hoc or weird (with JSON as column content in CSV)?

Irrespective of the other discussions (I'll read through them later!) I don't find it weird or ad-hoc at all, rather, I find the proposal quite consistent and feel it's a 'logical' next step or extension. I like it!

**Comment by Anaphory** [comment]
I'm really not sure, that's why I wonder whether we could even conceive such a thing.

The first thing I can think of that goes vaguely in this direction would be similar to virtual columns, but given that we [inherit virtual columns from CSVW](https://w3c.github.io/csvw/metadata/#use-of-virtual-columns), I don't think that's a sensible start for this thought experiment.

Browsing through the CSVW specs, I noticed [weak linking](https://w3c.github.io/csvw/metadata/#weak-linking-between-tables). With a probably more complicated set of special cases than the ones you suggest (and starting with some specification of how to treat weak linking inside CLDF), we could have a column in the ValueTable that weakly links to the CodeTable in some cases, and to a different table (or just an ontology of numbers, yay :disappointed:) in other cases.

**Comment by xrotwang** [comment]
TBH, I find it difficult to compare concrete implementation proposals with thought experiments :)

**Comment by xrotwang** [comment]
@Anaphory @davidainman here's how I would imagine typed values to work:
https://github.com/cldf/pycldf/pull/135/files#diff-85bf2019559734a47ac9b8e371220fa7bfe3ed59b5d4401f61f49bdb0a264df7

This really does not require much code, see https://github.com/cldf/pycldf/pull/135/files#diff-03d1c88087d8b8c2f7f2afefe1dce69db8198d8734548999ffcbe3f8f99facf9
In particular, I think it is transparent enough to also work with other toolchains - i.e. outside of `pycldf`.

**Comment by LinguList** [comment]
I agree with @xrotwang. This seems to be the currently easiest and most straightforward solution.

**Comment by davidainman** [comment]
@PaprikaSteiger is working on this database to create a CLLD web app and this workaround causes a problem with the SQL foreign keys. If integers lack a CodeID, then the CodeID column cannot be declared a foreign key (because there are empty cells). There are two workarounds to this, as we understand it:

(1) We do not declare CodeID as a foreign key (but this breaks the database structure)
(2) We create a fake CodeID for integers that points somewhere saying "Hey, this is an integer, this is not a real value, go look at the values column"

I'm not sure if one of these is better than the other, or if this breaks this integer workaround totally. (Feel free to chime in, @PaprikaSteiger, since you are more familiar with it!)

**Comment by xrotwang** [comment]
I don't fully understand. Are we talking about the SQL schema of the clld web app here? If so, that could be entirely separate from the CLDF data model, because loading CLDF data into the app is fully under your control, via the code you write in `scripts/initializedb.py`.

If we are talking about the CLDF data model - and possibly the SQLite db that can be created from it via `cldf createdb`, then I could see the problem. Using `Code_ID` as foreign key for a couple of parameters but not for others wouldn't work. IIRC, the original problem was that you wanted to have typed values for some parameters, right? Maybe my recipe for typed values as used in this test https://github.com/cldf/pycldf/blob/032345fed1b29a8799233d1961f492d7b992a540/tests/test_orm.py#L135-L166 would be a better option then? The idea is that all values are serialized as strings (which fits with `Value`), but the ParameterTable has enough info to deserialize the value into a typed object.

**Comment by davidainman** [comment]
Yes, we are talking about the SQL schema of the CLLD app (I believe @PaprikaSteiger is using cldf createdb). The original issue is we wanted to have open-ended real number values for some parameters, which CLDF doesn't really support by default. The options were to create a special code ID for every numeral in the database, or this workaround where some parameters had a datatype "integer" which signaled that parameters of this type had no CodeID, but rather a fixed value.

I'm not sure if I fully follow the test_orm code (I have only been peripherally involved in generating the code to port our flat database structure into validated CLDF). If I follow, it does away with the codes table altogether? I'm not sure if this matches totally what CLDF was supposed to encode (i.e., fixed values), but I don't see whether there's a way around a concept like "real numbers" otherwise. It's also not clear to me if this would fix our issues in setting up a clld app.

**Comment by xrotwang** [comment]
If it's the SQL of the clld app, then it's presumably created via `clld initdb` - which is just a wrapper around the code you provide yourselves in `yourapp/scripts/initializedb.py`. That's what I meant above, that the schema of the clld app is fully under your control, i.e. must not match the CLDF dataset schema exactly.

The CLDF [ValueTable](https://github.com/cldf/cldf/blob/master/components/values/ValueTable-metadata.json) specifies `Code_ID` as optional. So it's completely ok to have some categorical parameters, with valid codes listed in CodeTable and consequently non-empty `Code_ID` for values in ValueTable - and others with empty `Code_ID`. For the non-categorical parameters the question arises how to store the typed values, e.g. rational numbers in your case. CLDF doesn't have a clearcut solution for this. You can
- just serialize the value as string and put it in ValueTable `Value` - making sure the documentation of the data makes the data type clear
- add a column - e.g. `Value_Number` with appropriate type to ValueTable
- or use the recipe I linked to in pycldf's tests, which is a somewhat a hybrid between the two options above: The `datatype` column added to ParameterTable is basically machine-readable documentation, with the added benefit of builtin support in pycldf.

**Comment by PaprikaSteiger** [comment]
Thanks for your elaboration. 
I think the problem is not in the `yourapp/scripts/initializedb.py` but in `yourapp/models.py`. I derived an `OOAValue` class from `Value` and declared the  `Code_ID` as a foreign key pointing to the primary key of a `DomainElement`. Did I understand you correctly that I should change it to a normal column and add the ValueTable in `datatables.py` with a link column to the DomainTable?

**Comment by xrotwang** [comment]
`Value` already has a foreign key to `DomainElement`, see
https://github.com/clld/clld/blob/ddf56c8b9591d50ef39ccb66a3ae499dade0ab20/src/clld/db/models/value.py#L52-L62

`Code_ID` (or more correctly, the column with propertyUrl `...#codeReference`) will typically used to instantiate such a relation between `Value` and `DomainElement`. See
https://github.com/clld/clld/blob/ddf56c8b9591d50ef39ccb66a3ae499dade0ab20/src/clld/project_template/%7B%7Bcookiecutter.directory_name%7D%7D/%7B%7Bcookiecutter.directory_name%7D%7D/scripts/initializedb.py#L140-L147

This will not work if you have not-null values in `Code_ID` which do not point to anything in `CodeTable` - e.g. if you put any integers into `Code_ID`. So in this case, I would indeed load the values of `Code_ID` into a non-foreignkey column.

**Comment by xrotwang** [comment]
We should have a solution to these issues spelt out in the FAQ.
