### ISSUE TITLE
How to treat words that belong to multiple cognate sets

### ISSUE THREAD

**Issue by martino-vic** [cldf/cldf#129]
As I have understood, the column cognacy requires exactly one integer that indicates to which cognate set a word belongs. How should words be treated that belong to multiple ones?

To give an example from data that I've just been working on: Hungarian <bűbáj> is a loanword from West Old Turkic, it's an intransparent compound from <bű> and <báj> for both of which there is a separate entry in the table. The way I'm currently treating this is that I'm simply omitting it, but that can hardly be the preferred alternative.

So I was wondering how to treat these kind of entries ideally. Maybe adding multiple integers to column "Cognacy"?

**Comment by xrotwang** [comment]
This is more a `lexibank` than a general CLDF issue, since `Cognacy` is defined for lexibank datasets, see https://github.com/lexibank/pylexibank/blob/8ae170cecb67f450b7a8cbaa56ded94281944b0f/src/pylexibank/models.py#L85 - but not in the [CLDF ontology](https://cldf.clld.org/v1.0/terms.rdf).

Anyway, even in lexibank, this column is only there to preserve any dataset-specific way to indicate cognacy. The "CLDF way" to assign forms to cognate sets (and which is also [supported by pylexibank](https://github.com/lexibank/pylexibank/blob/8ae170cecb67f450b7a8cbaa56ded94281944b0f/src/pylexibank/cldf.py#L259-L274)) is by adding rows to a [CognateTable](https://github.com/cldf/cldf/tree/master/components/cognates). This table reverses the link, i.e. the cognate links to the form. So adding multiple cognates linking to the same form is fully supported.

**Comment by martino-vic** [comment]
Thank you for the answer! Just need to double check if I've understood it correctly, so I've transferred this to lexibank and closing this issue here now. Thanks again a lot for the help!
