### ISSUE TITLE
Macroarea as subtype of a more general “named area” property?

### ISSUE THREAD

**Issue by Anaphory** [cldf/cldf#45]
I have named regions in my database, and I think that might be a data type worth including in future CLDF releases. Macroareas (https://github.com/glottobank/cldf/blob/ff33e40dbccabaf1191f08eb8f486a13343a6f5b/terms.rdf#L272) are then an obvious, semantically well-defined subtype of named areas. Countries could be another type of named area.

While that type of data can be programatically extracted from the geo-coordinates using some set of covering polygons, it does have value in itself, I think.

**Comment by xrotwang** [comment]
So far I'd say the guiding principle for the ontology is "whatever has
useful semantics for analysis" rather than trying to model whatever we will
encounter in datasets. Your regions may be useful for you, but do they have
commonly understood semantics? E.g. macroareas are meant to partition the
set of languages in a particular way.

Am 20.10.2017 4:54 nachm. schrieb "Gereon Kaiping" <notifications@github.com

**Comment by Anaphory** [comment]
I think that type of area assignments would be generally useful for discrete phylogeographic analyses, yes. It's not a thing I have seen used in linguistic phylogenetics much, but that's the use case I was just musing about, which brought this up.

For a concrete analysis, it would likely be necessary to specify the relations of the regions to each other, but that holds for discrete typological values, as well; the difference between both is very much the semantics.

**Comment by xrotwang** [comment]
Ok, so could we defer this, i.e. use discrete typological values as workaround for less well-specified areal categories? Feel free to re-open if you have a concrete proposal.
