### ISSUE TITLE
Keep naming of columns similar to names in ontology

### ISSUE THREAD

**Issue by cysouw** [cldf/cldf#53]
This just took me some time to figure out, and left me with quite some confusion, so maybe it would be good to change this:

The names of columns in the description of the tables (e.g. [`formTable`](https://github.com/cldf/cldf/blob/master/components/forms/FormTable-metadata.json)) are linked to properties in the ontology in `terms.rdf`. For clarity, I would propose to use the ontology names as column names to avoid confusion.

For example, in [`formTable`](https://github.com/cldf/cldf/blob/master/components/forms/FormTable-metadata.json):

- `"name" = "Form"` can simply be changed to `"name" = "LexicalUnit"`
- `"name" = "Segments"` can simply be changed to `"name" = "soundSequence"`

As a general rule-of-thumb, we can keep `_ID` instead of `Reference`, so we use `"name" = "Language_ID"` instead of the literal copy from the ontology, which would be `"name" = "languageReference"`.

Of course these are just names, and they have to be explicitly referenced in the meta-data of each dataset, so you can change it to whatever you want. However, in the description of the CLDF I think it is better to make this easier to grasp immediately.

If you agree, I'll make a pull request with such changes

**Comment by LinguList** [comment]
Unfortunately, this is not a simple change of cldf, but it'll require to change the converter to PDF in Lingpy and a couple of other things. LexicalUnit is the term by GOLD as is SoundSequence. I think we may should retain the right to have better terms than GOLD has in those cases, and I'd say that both Segments and Form are better, and we had a lot of discussions in the past, on how to name those columns.

**Comment by xrotwang** [comment]
Generally, identification of columns relevant for CLDF goes by propertyUrl.
We may document the ontology somewhat better, to highlight that the
proposed column label is just one option. Using the local names of
properties in the ontology for columns may just lead to invalid shortcut
inferences - e.g. looking up names in the ontology instead of propertyUrls.

Am 26.11.2017 10:47 vorm. schrieb "Johann-Mattis List" <
notifications@github.com>:

Unfortunately, this is not a simple change of cldf, but it'll require to
change the converter to PDF in Lingpy and a couple of other things.
LexicalUnit is the term by GOLD as is SoundSequence. I think we may should
retain the right to have better terms than GOLD has in those cases, and I'd
say that both Segments and Form are better, and we had a lot of discussions
in the past, on how to name those columns.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cldf/cldf/issues/53#issuecomment-346995959>, or mute
the thread

**Comment by cysouw** [comment]
OK, also fine with me.

However, the documentation should become clearer :-), and the Readme is already much too long.

Would you agree to a directory `documentation` in the CLDF? Then I'll put all lowercased `.md` documents from the top level in there (currently `faq` and `wordlist`), and make separate documents out of the current Readme. The new readme will then only be a short introduction with links to the various files in the documentation.

and I will add something about the column naming...

**Comment by xrotwang** [comment]
I kind of like the fact that the spec is just one page. (Faq is not core
part and wordlist is obsolete). A short introduction is the website
http://cldf.clld.org

So I'm quite happy with the status quo in terms of doc organisation. Better
wording is always welcome, though.

Am 26.11.2017 11:12 vorm. schrieb "Michael Cysouw" <notifications@github.com

**Comment by cysouw** [comment]
OK, I'll send a proposal for an update to the readme
