### ISSUE TITLE
Can we handle individual variation?

### ISSUE THREAD

**Issue by LinguList** [cldf/cldf#68]
Maybe a stupid question, but imagine the following scenarios:

* I have a dataset for 100 words elicited by 200 speakers of the same language and want to represent this data in cldf, can I assign each speaker the same glottocode, but specify the idiolect that they speak (maybe by just giving anonymized numbers)?
* same for cases where I have close dialects not yet in glottolog: I select the upper language, the standard, and indicate that the two are separate varieties

I think, for the first scenario, we should definitely allow for some standardization (even if it's just a statement in the metadata indicating that this is individual/idiolect-level variation). For the second, we would further profit from some procedure by which we could queue new dialect locations for appearance in glottolog, similar to the way that we decided now to allow for concept-identifiers not yet in concepticon by using a gloss prefixed by an exclamation mark, as this will help us to work consistently when developing one dataset and then adding all missing varieties or concept sets in one flush.

**Comment by tresoldi** [comment]
Does not seem stupid at all -- besides your scenarios, it could also be a solution for datasets exploring dimensions of language variation within the same community (not really in terms of medium, but diachronic, diastratic, and diaphasic variations would be primary candidates).

But in terms of allowed columns/fields, isn't that already possible? Or you mean formalizing what is possible?

**Comment by LinguList** [comment]
Formalizing, I'd say: people should explicitly decide whether their data is individuals or dialects which are below the glottocode. For concepticon-concepts, we are currently testing to allow users to use a "!NEWCONCEPT" without an ID so they can preliminarily define concepts for their dataset.

**Comment by tresoldi** [comment]
That's good, it would make thr solution of conflicts easier (even
semi-automatico).

Em 11 de jan de 2018 11:48 AM, "Johann-Mattis List" <
notifications@github.com> escreveu:

**Comment by HedvigS** [comment]
I also think it's a good question and a good solution. It would make people like us in the Wellsprings project very happy.

As glottocodes work now there is no way of differentiating between languoid, higher nodes and dialects right? Like I can't tell from the code itself where on the tree it's likely to be. Example:

* swed1254 = Swedish (national language)
* svea1239 = sveamål (dialect of swedish above)
* east2781 = east swedic (subgrouping of germanic)
* dale1238 = Dalecarlian (other language within sweden, not in east swedic)

My understanding is that @d97hah @xrotwang and @haspelmath are quite liberal in allowing addition of new dialects. You can understand that something is a dialect either by learning that they are a sub-node of a languoid or consulting their "level" (family/languoid/dialect). I hope this is the correct account.

Instead of differentiating between dialects and individuals (things under "languoid"), it's probably better to differentiate between all of languages, dialects and higher nodes on one side and individuals (the current glottocode for dialect/languoid + a few more digits) on the other, for example by adding a few more digits to the dialect/languoid glottocode.

**Comment by agricolamz** [comment]
After @tresoldi comment I realized that it is good to have some notion of time for the scenario when I work with the same speakers with ten years gap. The codes for language and speaker should be the same, but the time stamps are different. It is really rare situation, but I've heard about such cases.

**Comment by LinguList** [comment]
Adding times is straightforward by putting a Year or similar field in the `languages.csv`. In principle, since we can use our own language identifiers, in this file, the question of how to handle dialects and speaker-variation is also easily solvable. However, having some convention, recommendation, or even prescription in these cases seems to be useful, also based on the reactions. It seems we need to handle:

* dialect varieties not yet in glottolog (which could be similar to languages not yet in glottolog). As far as I understand, especially geolocation is crucial here, so geolocation should be added in the case that a variety is not yet in glottolog
*  individual variation of one language by sampling different speakers (here, some recommendations are needed to document useful information, as the year or even date when the data were collected)

Ideally, we'd need an example for both cases. For the first, the [Chinese dialect data](https://github.com/digling/cddb/blob/master/varieties/languages.geojson) I have started to collect and combine will offer useful use-cases. For the second, I am not sure yet.

**Comment by Anaphory** [comment]
If we had terms for `date`, `speakerReference` and `SpeakerTable`, you could add a `speakerReference` column and a `date` column to your `FormTable`, and if the languoid is identical for all those forms turn it into a virtual column. We don't have these terms yet (but these seem the canonical choices to me), but that should not keep you from trying them out and showing that they are useful.

## Reasoning
Putting time stamps on things (in my case sound changes, in @LinguList's case lects, in @agricolamz' case utterances) is often useful anyway, so that would not be an explosion of things. I would call that term `date`, not `Year`, because then the user is free to take whatever level of detail they need.

There is significant use for speaker data, probably enough to include them. I don't think speakers should be grouped under languages. If I think of my colleagues' data, multilingual speakers are an important point of research, which this would not be able to represent. Adding an optional `Speaker` column to form/example tables would work, metadata about speakers would then go to a separate table.

If you write your code for inter-speaker variation using stuff like `dataset["FormTable", "speakerReference"]`, you are bound to call your column `speakerReference` and not `Speaker_ID` or something like that until such a term makes it into the standard, but once it does, code still works when applied to new data sets which use the new terms.

If people start writing software for which the interviewer would be relevant, or the location of the interview, the procedure should probably the same: Write example code (or describe your application) first, using terms which are as generic as possible for the code to be still applicable and which follow the structure of already existing terms (`camelCase`, `CamelTable`, `camelReference`, …), and have a specific discussion then. If interviewers are never needed in our automatic analyses, there is no need to pin down the semantics of that term for interoperability between different programs using that data.

**Comment by xrotwang** [comment]
@Anaphory If we'd call the term `timestamp` and only require that it is something that can be linearily ordered, would this already make it possible to store (at least subsets) of ELAN in CLDF?

**Comment by Anaphory** [comment]
@xrotwang I'll try to find out. How far did we get discussing media file support?

`timestamp` might be as confusing for historical linguists as `date` would be for users of ELAN, but programmers can abstract away from either. Also, `time` might be a good compromise, or might be even worse, what do you think?

**Comment by xrotwang** [comment]
I think `timestamp` has clearer semantics than `time`, since the latter may be confused with durations, etc.

Regarding media file support, I'd propose to discuss this in a different issue. My use cases so far would require audio and image files in a many-to-many relation to rows in various other CLDF tables. So I'm leaning towards an additional table `FilesTable`, using the MD5 sum as primary key and providing metadata in various columns, including access descriptions, e.g. a URL, possibly using the `file://` scheme.

**Comment by xrotwang** [comment]
Coming back to this, I'd like to comment on three issues raised here:

**Individual variation**:  After having thought about this a bit more, also triggered by encounters with multilingual and sociolinguistic data, I'd say `LanguageTable` really is about the language-system-level objects of research. So if a study is about individual variation, `LanguageTable` should list individuals.

**Date**: I think a date property without clear-cut semantics wouldn't be a candidate for standardization. If the interpretation of the column is dataset specific, I'd say just using any of the date-related [DCTERMS](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/) properties as `propertyUrl` is good enough.

**SpeakerTable**: Couldn't references to speakers handled using the `ContributionTable`, introduced in [CLDF 1.1](https://github.com/cldf/cldf/blob/master/CHANGELOG.md#v11---2021-04-28)?

I'm closing this issue now, but feel free to open (possibly more focused) issues targeting aspects discussed here if needed.
